# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Maison Dr. Dermenaki®
# Description of the Site
description: FACE INSTITUTE (Science, Precision, Harmony)
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: rfcaspiani@yahoo.it
facebook_username: Coming up soon
twitter_username: Coming up soon
instagram_username: Coming up soon
linkedin_username: Coming up soon
github_username:  Coming up soon
youtube_channel_id: Coming up soon
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Maison Dr. Dermenaki®
# URL for the Image of the Author
author-image: https://i.postimg.cc/wMCZFszb/Maison12.jpg
# 60 Words About the Author
author-about: I hold degrees in both Dentistry and Medicine from the University of Pavia, Italy. Immediately after graduation, I began working in both hospital settings and private practice as a dentist, performing a range of oral surgery procedures. I later pursued advanced training in Oral and Maxillofacial Surgery, primarily based in Milan, Italy. During my residency, I had the privilege of collaborating with and learning from renowned surgeons in Switzerland, Austria and Germany, where I regularly trained and practiced in plastic surgery, head and neck surgery, and oral and maxillofacial surgery units. My clinical practice encompasses a wide range of procedures, including head and neck oncology, facial trauma management, oral surgery, dental implantology, wisdom tooth extraction, facial aesthetic surgery, and orthognathic surgery. Through my education and training, I have developed a comprehensive understanding of facial and neck anatomy, coupled with extensive surgical experience. This foundation allows me to approach each case with precision, safety, and a strong aesthetic sensibility. I am deeply committed to integrating the latest surgical innovations and evidence-based practices to achieve the highest standards of functional and cosmetic outcomes for my patients.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/













