# WhatATheme
markdown: kramdown

# URL of the Site
url: ''
# Base URL of the Site (i.e., Name of the Repository in which the Site is hosted)
baseurl: 

# Title of the Site
title: Maison Dr. Dermenaki
# Description of the Site
description: FACE INSTITUTE (Science, Precision, Harmony)
# URL of Image of the Site
site-image: /WhatATheme/assets/images/meta.jpg
# Keywords of the Site
site-keywords: Site, Template, Theme
# URL for the Image of custom Favicon
favicon-url: 

# URL of the Image of Custom Hero Image (i.e., the image in the background of the very first section of the Homepage)
heroimage: https://images.pexels.com/photos/220444/pexels-photo-220444.jpeg?auto=compress&cs=tinysrgb&dpr=2&h=650&w=940

# Social Media and Contact
# If you don't want to use any icon, you can leave them blank.
email: rfcaspiani@yahoo.it
facebook_username: Coming up soon
twitter_username: Coming up soon
instagram_username: Coming up soon
linkedin_username: Coming up soon
github_username:  Coming up soon
youtube_channel_id: Coming up soon
reddit_username: /
behance_username: /
dribbble_username: /
spotify_username: /

# Google Analytics
google-analytics: UA-163806439-1

# Disqus
disqus-shortname: thedevslot

# Name of the Author
author-name: Maison Dr. Dermenaki
# URL for the Image of the Author
author-image: https://i.postimg.cc/LXxt4kwM/IMG-2786.jpg
# 60 Words About the Author
author-about: I graduated from both Dental School and Medical School at the University of Pavia, Italy, before pursuing advanced training in Oral and Maxillofacial Surgery in Milan, Italy. My clinical practice focuses on a broad spectrum of procedures, including head and neck oncology, facial traumatology, oral surgery, dental implantology, wisdom tooth extraction, facial aesthetic surgery, and orthognathic surgery. Throughout my education and training, I have developed an in-depth knowledge of facial and neck anatomy, combined with extensive surgical experience, enabling me to approach each case with precision, safety, and aesthetic consideration. I am committed to integrating the latest surgical techniques and evidence-based practices to deliver optimal functional and cosmetic outcomes for my patients.
# URL to the Author's Profile (i.e., Github, Twitter, Stackoverflow, etc)
author-url: https://github.com/thedevslot

# SASS
sass:
  sass_dir: _sass
  style: compressed

# Build settings
plugins:
  - jekyll-admin
  - jekyll-feed

# Permalink
permalink: "blog/:title"

# Compress
compress_html:
  clippings: all

# Defaults
defaults:
  -
    scope:
      type: 'posts'
    values:
      layout: post
      post-image: ""
      description: ""
      tags:
        - ""
  -
    scope:
      type: 'pages'
    values:
      layout: page

# Exclude
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/





